# Generated by Django 3.2.12 on 2022-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='img',
            field=models.ImageField(default='ddddddddd', upload_to='Gallery'),
            preserve_default=False,
        ),
    ]
